# Basic site settings
title: "My Awesome Site"        # Replace with your site's title
description: "A simple description for my Jekyll site"
url: "https://avinash979309.github.io/CSP203-website" # Replace with your site URL
baseurl: "/CSP203-website" # Replace with your repository name, or leave blank for root domain

# Author information
author:
  name: "Avinash Patel"
  email: "avinashp@iitbhilai.ac.in"

# Theme and layout settings
theme: jekyll-theme-primer       # GitHub Pages-supported theme
markdown: kramdown               # Markdown engine

# Jekyll build settings
plugins:
  - jekyll-seo-tag               # For better SEO
  - jekyll-gist                  # To embed GitHub gists
  - jekyll-paginate              # Pagination support
  - jekyll-sitemap               # Generate a sitemap
  - jekyll-feed                  # Generate an RSS feed
  - jekyll-github-metadata       # Add GitHub repository metadata
  - jekyll-commonmark-ghpages    # Support CommonMark for Markdown
  - jekyll-titles-from-headings  # Use headings for page titles

paginate: 5                      # Number of posts per page for pagination
paginate_path: "/page:num/"      # URL format for pagination

# Defaults for pages
defaults:
  - scope:
      path: ""                   # All files
    values:
      layout: "default"          # Default layout

# Exclude files or directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - venv                        # Exclude Python virtual environment if it exists
  - README.md
  - .gitignore
  - .github                     # Exclude GitHub Actions configuration files

# Configuration for GitHub Pages
github:
  is_project_page: true         # Set to true if the site is hosted on GitHub Pages

# Output settings
markdown_ext: "md,markdown"     # Extensions for Markdown files
permalink: "/:categories/:title/"

# Other settings
collections:
  posts:
    output: true                # Output posts as part of the build
